spring.application.name=inicio
spring.profiles.active=conexion-empresa

server.port=8080
springdoc.packages-to-scan=com.proyecto.inicio.controller

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gestion_procesos
spring.datasource.username=gestor_procesos
spring.datasource.password=web.onomatopeya
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true