server.address=127.0.0.1
server.port=8080

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gestion_procesos
spring.datasource.username=gestor_procesos
spring.datasource.password=web.onomatopeya
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false