spring.application.name=inicio

spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_procesos
spring.datasource.username=gestor_procesos
spring.datasource.password= web.onomatopeya

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true