spring.application.name=inicio

spring.datasource.url=jdbc:postgresql://localhost:5433/onomatopeya
spring.datasource.username=onomatopeya_p
spring.datasource.password=Laura.10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true