-- Propuesta del 27/09/2026 para revisar con Laura y Camila.
-- No pertenece a src/main/resources y Spring no la ejecuta automáticamente.
-- Preparada para las 8 tablas observadas en gestion_procesos.
-- El ensayo termina en ROLLBACK: no deja cambios persistentes.
-- Incluso un ensayo toma bloqueos. Probar primero en una copia aislada.
\set ON_ERROR_STOP on

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
SET LOCAL search_path = public, pg_catalog;

DO $revision$
DECLARE
    tabla text;
BEGIN
    IF current_database() <> 'gestion_procesos' THEN
        RAISE EXCEPTION 'Base distinta de gestion_procesos. Revisar el destino antes de continuar.';
    END IF;

    FOREACH tabla IN ARRAY ARRAY[
        'empresa', 'usuario', 'proceso', 'rol_proceso',
        'pool', 'lane', 'acceso_proceso', 'historial_cambio'
    ] LOOP
        IF to_regclass('public.' || tabla) IS NULL THEN
            RAISE EXCEPTION 'Falta la tabla previa public.%. No ejecutar sobre una base vacía.', tabla;
        END IF;
    END LOOP;

    FOREACH tabla IN ARRAY ARRAY[
        'nodo', 'arco', 'mensaje', 'campo_mensaje',
        'flujo_mensaje', 'uso_mensaje_actividad', 'permiso_estructura'
    ] LOOP
        IF to_regclass('public.' || tabla) IS NOT NULL THEN
            RAISE EXCEPTION 'public.% ya existe. Revisar el esquema; no se sobrescriben tablas.', tabla;
        END IF;
    END LOOP;

    IF EXISTS (SELECT 1 FROM public.empresa WHERE correo_contacto IS NULL) THEN
        RAISE EXCEPTION 'Hay empresas sin correo. Laura debe revisar esos datos; no se rellenan automáticamente.';
    END IF;
END;
$revision$;

-- Ampliar longitudes conserva los valores actuales y coincide con las entidades.
-- El NIT único, los IDs y los registros existentes se conservan.
ALTER TABLE public.empresa
    ALTER COLUMN nit TYPE varchar(255),
    ALTER COLUMN correo_contacto TYPE varchar(255),
    ALTER COLUMN correo_contacto SET NOT NULL;

-- Actividad, Evento y Gateway comparten esta tabla mediante tipo_nodo.
-- lane_id y tipo_actividad solo son obligatorios en una ACTIVIDAD.
CREATE TABLE public.nodo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_nodo varchar(20) NOT NULL,
    proceso_id bigint NOT NULL REFERENCES public.proceso(id),
    pool_id bigint NOT NULL REFERENCES public.pool(id),
    nombre varchar(150) NOT NULL,
    posicion_x integer NOT NULL,
    posicion_y integer NOT NULL,
    ancho integer NOT NULL,
    alto integer NOT NULL,
    estado varchar(20) NOT NULL,
    tipo_actividad varchar(20),
    lane_id bigint REFERENCES public.lane(id),
    tipo_gateway varchar(20),
    direccion_gateway varchar(20),
    tipo_evento varchar(20),
    naturaleza_evento varchar(20),
    operacion_mensaje varchar(20),
    CONSTRAINT ck_nodo_tipo CHECK (tipo_nodo IN ('ACTIVIDAD', 'GATEWAY', 'EVENTO')),
    CONSTRAINT ck_nodo_estado CHECK (estado IN ('BORRADOR', 'ACTIVO', 'RETIRADO')),
    CONSTRAINT ck_actividad_tipo CHECK (tipo_actividad IN ('TAREA', 'ENVIO')),
    CONSTRAINT ck_actividad_lane_tipo CHECK (
        tipo_nodo <> 'ACTIVIDAD' OR (lane_id IS NOT NULL AND tipo_actividad IS NOT NULL)
    ),
    CONSTRAINT ck_gateway_tipo CHECK (tipo_gateway IN ('EXCLUSIVO', 'PARALELO', 'INCLUSIVO')),
    CONSTRAINT ck_gateway_direccion CHECK (direccion_gateway IN ('DIVERGENCIA', 'CONVERGENCIA')),
    CONSTRAINT ck_evento_tipo CHECK (tipo_evento IN ('INICIO', 'INTERMEDIO', 'FIN')),
    CONSTRAINT ck_evento_naturaleza CHECK (naturaleza_evento IN ('NORMAL', 'MENSAJE')),
    CONSTRAINT ck_evento_operacion CHECK (operacion_mensaje IN ('ENVIO', 'RECEPCION'))
);

CREATE TABLE public.arco (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id bigint NOT NULL REFERENCES public.proceso(id),
    pool_id bigint NOT NULL REFERENCES public.pool(id),
    origen_id bigint NOT NULL REFERENCES public.nodo(id),
    destino_id bigint NOT NULL REFERENCES public.nodo(id),
    etiqueta varchar(150),
    condicion_salida text,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_arco_origen_destino UNIQUE (origen_id, destino_id)
);

-- Primero se crea Mensaje sin la FK de correlación, pues CampoMensaje aún no existe.
CREATE TABLE public.mensaje (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nodo_id bigint NOT NULL REFERENCES public.nodo(id),
    sentido varchar(255) NOT NULL,
    nombre varchar(150) NOT NULL,
    origen_externo boolean NOT NULL DEFAULT false,
    correlacion_tipo varchar(255),
    correlacion_negocio varchar(150),
    correlacion_campo_id bigint,
    politica_sin_correspondencia varchar(255),
    activo boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_mensaje_nodo UNIQUE (nodo_id),
    CONSTRAINT ck_mensaje_sentido CHECK (sentido IN ('ENVIO', 'RECEPCION')),
    CONSTRAINT ck_mensaje_correlacion CHECK (correlacion_tipo IN ('NEGOCIO', 'CAMPO')),
    CONSTRAINT ck_mensaje_politica CHECK (politica_sin_correspondencia IN ('DESCARTAR', 'INICIAR_CASO'))
);

CREATE TABLE public.campo_mensaje (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id bigint NOT NULL REFERENCES public.mensaje(id),
    nombre varchar(100) NOT NULL,
    tipo_dato varchar(255) NOT NULL,
    orden integer NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_campo_mensaje_nombre UNIQUE (mensaje_id, nombre),
    CONSTRAINT ck_campo_tipo CHECK (tipo_dato IN ('TEXTO', 'ENTERO', 'DECIMAL', 'BOOLEANO', 'FECHA', 'FECHA_HORA'))
);

ALTER TABLE public.mensaje ADD CONSTRAINT fk_mensaje_correlacion_campo
    FOREIGN KEY (correlacion_campo_id) REFERENCES public.campo_mensaje(id);

CREATE TABLE public.flujo_mensaje (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id bigint NOT NULL REFERENCES public.proceso(id),
    pool_origen_id bigint NOT NULL REFERENCES public.pool(id),
    pool_destino_id bigint NOT NULL REFERENCES public.pool(id),
    nodo_origen_id bigint REFERENCES public.nodo(id),
    nodo_destino_id bigint REFERENCES public.nodo(id),
    tipo_destino varchar(255),
    politica_fallo varchar(255),
    actividad_error_id bigint REFERENCES public.nodo(id),
    activo boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_flujo_destino CHECK (tipo_destino IN ('CORREO', 'SERVICIO_WEB', 'COLA')),
    CONSTRAINT ck_flujo_fallo CHECK (politica_fallo IN ('CONTINUAR', 'DERIVAR', 'FINALIZAR'))
);

CREATE TABLE public.uso_mensaje_actividad (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id bigint NOT NULL REFERENCES public.mensaje(id),
    actividad_id bigint NOT NULL REFERENCES public.nodo(id),
    activo boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_uso_mensaje_actividad UNIQUE (mensaje_id, actividad_id)
);

CREATE TABLE public.permiso_estructura (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id bigint NOT NULL REFERENCES public.proceso(id),
    rol_acceso varchar(255) NOT NULL,
    recurso varchar(255) NOT NULL,
    accion varchar(255) NOT NULL,
    permitido boolean NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_permiso_estructura UNIQUE (proceso_id, rol_acceso, recurso, accion),
    CONSTRAINT ck_permiso_rol CHECK (rol_acceso IN ('ADMINISTRADOR', 'EDITOR', 'LECTURA')),
    CONSTRAINT ck_permiso_recurso CHECK (recurso IN ('POOL', 'LANE')),
    CONSTRAINT ck_permiso_accion CHECK (accion IN ('CREAR', 'EDITAR', 'RETIRAR'))
);

-- Índices de relaciones no cubiertas por el comienzo de una clave única.
CREATE INDEX ix_nodo_proceso ON public.nodo(proceso_id);
CREATE INDEX ix_nodo_pool ON public.nodo(pool_id);
CREATE INDEX ix_nodo_lane ON public.nodo(lane_id);
CREATE INDEX ix_arco_proceso ON public.arco(proceso_id);
CREATE INDEX ix_arco_pool ON public.arco(pool_id);
CREATE INDEX ix_arco_destino ON public.arco(destino_id);
CREATE INDEX ix_mensaje_correlacion ON public.mensaje(correlacion_campo_id);
CREATE INDEX ix_flujo_proceso ON public.flujo_mensaje(proceso_id);
CREATE INDEX ix_flujo_pool_origen ON public.flujo_mensaje(pool_origen_id);
CREATE INDEX ix_flujo_pool_destino ON public.flujo_mensaje(pool_destino_id);
CREATE INDEX ix_flujo_nodo_origen ON public.flujo_mensaje(nodo_origen_id);
CREATE INDEX ix_flujo_nodo_destino ON public.flujo_mensaje(nodo_destino_id);
CREATE INDEX ix_flujo_actividad_error ON public.flujo_mensaje(actividad_error_id);
CREATE INDEX ix_uso_actividad ON public.uso_mensaje_actividad(actividad_id);

-- Comprobaciones dentro del ensayo. Al terminar se revierte toda la transacción.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;

SELECT count(*) AS empresas,
       count(*) FILTER (WHERE correo_contacto IS NULL) AS empresas_sin_correo
FROM public.empresa;

ROLLBACK;
-- Solo después de aprobación y pruebas en copia, sustituir el ROLLBACK por COMMIT.
-- No ejecutar también propuesta-esquema-nodos.sql: su ajuste ya está incluido aquí.
